# Generated by Django 5.0.6 on 2024-05-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
                ('endereco', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=14)),
                ('cnpj', models.CharField(max_length=14)),
                ('pagamento', models.CharField(max_length=75)),
                ('descricao', models.TextField()),
                ('senha', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Loja',
            },
        ),
        migrations.CreateModel(
            name='Lojistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
                ('data', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=14)),
                ('cpf', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Lojista',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('codigo_da_roupa', models.CharField(max_length=5)),
                ('imagem_produto', models.ImageField(upload_to='')),
                ('preco', models.FloatField()),
                ('descricao', models.TextField()),
                ('numero_produtos_inicial', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Produto',
            },
        ),
    ]
