# Generated by Django 5.0.6 on 2024-06-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastramento', '0002_alter_produtos_imagem_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='codigo_da_roupa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='imagem_produto',
            field=models.ImageField(upload_to='img_produtos/'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name=''),
        ),
    ]
