# Generated by Django 5.0.6 on 2024-06-07 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastramento', '0004_produtos_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojas',
            name='lojista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastramento.lojistas'),
        ),
        migrations.AlterField(
            model_name='lojas',
            name='endereco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lojistas',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
