# Generated by Django 5.0.6 on 2024-06-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastramento', '0005_lojas_lojista_alter_lojas_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojas',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
    ]
