# Generated by Django 5.0.6 on 2024-06-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastramento', '0007_lojas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
